import { Medicine, Category } from './types';

export const HOSPITAL_NAME = "原研药目录";

export const MOCK_INVENTORY: Medicine[] = [
  // 心血管药
  {
    id: '1',
    name: '苯磺酸氨氯地平',
    brandName: '络活喜',
    category: Category.CARDIOVASCULAR,
    description: '降低血压，缓解心绞痛，调节血管压力。主要不良反应：下肢水肿、面部潮红、心悸、头晕。',
    form: '片剂',
    dosage: '5mg',
    price: 35.50,
    inStock: true,
  },
  {
    id: '2',
    name: '甲磺酸多沙唑嗪缓释片',
    brandName: '可多华',
    category: Category.CARDIOVASCULAR,
    description: '治疗前列腺增生和高血压。主要不良反应：体位性低血压、乏力、头痛、嗜睡。',
    form: '片剂',
    dosage: '4mg',
    price: 42.00,
    inStock: true,
  },
  {
    id: '3',
    name: '缬沙坦胶囊',
    brandName: '代文',
    category: Category.CARDIOVASCULAR,
    description: '降压，控制高血压，降低心血管并发症风险。主要不良反应：头晕、低血压、血钾升高。',
    form: '胶囊',
    dosage: '80mg',
    price: 38.00,
    inStock: true,
  },
  {
    id: '4',
    name: '琥珀酸美托洛尔缓释片',
    brandName: '倍他乐克',
    category: Category.CARDIOVASCULAR,
    description: '调节心脏功能，减慢心跳，降低心脏负担。主要不良反应：心动过缓、疲劳、肢端发冷。',
    form: '片剂',
    dosage: '47.5mg',
    price: 28.50,
    inStock: true,
  },
  {
    id: '5',
    name: '苯磺酸氨氯地平片',
    brandName: '施惠达',
    category: Category.CARDIOVASCULAR,
    description: '调节血管压力，降低血压 (国产)。主要不良反应：下肢水肿、头痛、面红。',
    form: '片剂',
    dosage: '2.5mg',
    price: 20.00,
    inStock: true,
  },
  {
    id: '6',
    name: '阿司匹林肠溶片',
    brandName: '拜阿司匹灵',
    category: Category.CARDIOVASCULAR,
    description: '预防脑缺血、心肌梗死及血栓。主要不良反应：胃肠道刺激（胃痛）、出血倾向。',
    form: '片剂',
    dosage: '100mg',
    price: 16.00,
    inStock: true,
  },
  {
    id: '7',
    name: '利伐沙班片',
    brandName: '拜瑞妥',
    category: Category.CARDIOVASCULAR,
    description: '抗凝血药物，预防和治疗血栓。主要不良反应：出血风险（牙龈出血、尿血等）、贫血。',
    form: '片剂',
    dosage: '10mg',
    price: 180.00,
    inStock: true,
  },
  {
    id: '8',
    name: '沙库巴曲缬沙坦钠片',
    brandName: '诺欣妥',
    category: Category.CARDIOVASCULAR,
    description: '治疗心力衰竭，降低心血管死亡和住院风险。主要不良反应：低血压、高血钾、肾功能损伤、头晕。',
    form: '片剂',
    dosage: '100mg',
    price: 120.00,
    inStock: true,
  },

  // 降血脂药
  {
    id: '9',
    name: '阿托伐他汀钙片',
    brandName: '立普妥',
    category: Category.LIPID_LOWERING,
    description: '治疗高胆固醇血症，预防冠心病。主要不良反应：肌肉酸痛、肝酶升高、消化不良。',
    form: '片剂',
    dosage: '20mg',
    price: 48.00,
    inStock: true,
  },
  {
    id: '10',
    name: '非诺贝特胶囊',
    brandName: '力平之',
    category: Category.LIPID_LOWERING,
    description: '降低甘油三酯和胆固醇。主要不良反应：胃肠不适、肝酶升高、肌肉疼痛。',
    form: '胶囊',
    dosage: '200mg',
    price: 36.00,
    inStock: true,
  },
  {
    id: '11',
    name: '瑞舒伐他汀钙片',
    brandName: '可定',
    category: Category.LIPID_LOWERING,
    description: '强效控制胆固醇，降低血管硬化风险。主要不良反应：肌肉疼痛/无力、头痛、肝功能异常。',
    form: '片剂',
    dosage: '10mg',
    price: 45.00,
    inStock: true,
  },

  // 胰岛素/降糖药
  {
    id: '12',
    name: '精蛋白人胰岛素混合注射液(30R)',
    brandName: '诺和灵30R',
    category: Category.DIABETES,
    description: '控制血糖（含30%短效和70%中效胰岛素）。主要不良反应：低血糖、体重增加、注射部位反应。',
    form: '注射液',
    dosage: '3ml:300IU',
    price: 55.00,
    inStock: true,
  },
  {
    id: '13',
    name: '盐酸二甲双胍片',
    brandName: '格华止',
    category: Category.DIABETES,
    description: '减少糖分产生和吸收，调节血糖（口服药）。主要不良反应：胃肠道反应（腹泻、恶心）、口中金属味。',
    form: '片剂',
    dosage: '0.5g',
    price: 25.00,
    inStock: true,
  },

  // 神经/精神系统药
  {
    id: '14',
    name: '盐酸舍曲林片',
    brandName: '左洛复',
    category: Category.NEURO_PSYCH,
    description: '调节情绪，治疗抑郁症和强迫症。主要不良反应：恶心、腹泻、失眠、性功能减退。',
    form: '片剂',
    dosage: '50mg',
    price: 40.00,
    inStock: true,
  },
  {
    id: '15',
    name: '盐酸文拉法辛缓释胶囊',
    brandName: '怡诺思',
    category: Category.NEURO_PSYCH,
    description: '调节神经递质，稳定情绪，抗抑郁焦虑。主要不良反应：恶心、口干、便秘、多汗。',
    form: '胶囊',
    dosage: '75mg',
    price: 65.00,
    inStock: true,
  },

  // 消炎止痛/骨关节药
  {
    id: '16',
    name: '塞来昔布胶囊',
    brandName: '西乐葆',
    category: Category.PAIN_JOINT,
    description: '消炎止痛，缓解骨关节炎及类风湿关节炎疼痛。主要不良反应：胃部不适、腹痛、心血管风险。',
    form: '胶囊',
    dosage: '200mg',
    price: 58.00,
    inStock: true,
  },

  // 肝胆系统药
  {
    id: '17',
    name: '水飞蓟素胶囊',
    brandName: '利加隆',
    category: Category.LIVER,
    description: '保护肝细胞，辅助治疗肝炎及脂肪肝。主要不良反应：偶见腹泻、口干（副作用较少）。',
    form: '胶囊',
    dosage: '140mg',
    price: 38.00,
    inStock: true,
  },

  // 甲状腺药
  {
    id: '18',
    name: '甲巯咪唑片',
    brandName: '赛治',
    category: Category.THYROID,
    description: '抑制甲状腺素合成，治疗甲状腺功能亢进症（甲亢）。主要不良反应：皮疹、瘙痒、肝功能异常、白细胞/粒细胞减少（需定期查血）。',
    form: '片剂',
    dosage: '10mg',
    price: 22.00,
    inStock: true,
  }
];
